### ISSUE TITLE
change password

### ISSUE THREAD

**Issue by prashant12it** [prashant12it/drugsafe#5]
Error message must be in red color.
"Current Password must be at least 6 characters in length. " is invalid error message. There should be only one error message for current password field i.e. "Current Password does not match.
![1](https://cloud.githubusercontent.com/assets/15067471/19620495/260f0800-989c-11e6-8ec2-636cf36f2ac7.png)
"

**Comment by SShalini** [comment]
its wrking proprely sr...:-)

**Comment by prashant12it** [comment]
resolved
